config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :links
	resources :origins
end

app/models/link.rb
require 'open-uri'

class Link < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :url, presence: true,
									format: /\A#{URI.regexp(%w(http https))}\z/
  validates :bunrui, presence: true
	validates :title, presence: true, on: :update
  has_many :origin

  def get_page_title
    charset = 'utf-8'
    html = open(url) do |f|
      charset = f.charset # 文字種別を取得
      f.read # htmlを読み込んで変数htmlに渡す
    end
    # htmlをパース(解析)してオブジェクトを生成
    doc = Nokogiri::HTML.parse(html, nil, charset)

    # タイトルを取り出す
    doc.title
    end
  end

app/models/origin.rb
class Origin < ActiveRecord::Base
  belongs_to :link
	belongs_to :user
  validates  :content, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :links
	has_many :origins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	private

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = 'Please log in.'
			redirect_to login_url
		end
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	before_action :logged_in_user, only: [:new, :create]
	before_action :set_link, only: [:edit, :update, :destroy]


	def new
		@link = Link.new
		@tags = Origin.where(user_id: @current_user.id) + init_tag
	end

	def edit
		@current_tag = Origin.where(user_id: User.find_by(id: session[:user_id])) + init_tag
	end

	def update
		if @link.update(link_params)
			flash[:success] = '変更を保存しました'
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def create
		@link = Link.new(link_params)
		@link.user_id = current_user.id
		if @link.valid?(:url)#valid?はrailsで有効であるかどうか検証する、単独使用可。
			@link.title = @link.get_page_title
		end
		if @link.save
			flash[:success] = 'リンクが作成されました'
			redirect_to root_path
		else
			flash[:success] = "リンクの作成に失敗しました"
			redirect_to new_link_path
		end
	end

	def destroy
		@link.destroy
		flash[:success] = 'リンクを削除しました'
		redirect_to :root
	end

	def show
		redirect_to root_path
	end


	private

	def link_params
		params.require(:link).permit(:url, :title, :bunrui)
	end

	def set_link
		@link = Link.find(params[:id])
	end
end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController

	before_action :logged_in_user
	before_action :set_origin, only: [:edit, :update, :destroy]


	def new
		@origin = Origin.new
	end

	def show
		@tags = Origin.where(user_id: @current_user.id)
	end

	def update
		if @origin.update(origin_params)
			flash[:success] = '変更を保存しました'
			redirect_to origin_path
		else
			render 'edit'
		end
	end

	def edit
		@links = Link.where(bunrui: @origin)
	end

	def create
		@origin = Origin.new(origin_params)
		@origin.user_id = current_user.id
		if @origin.save
			flash[:success] = 'タグを作成しました'
			redirect_to origin_path(current_user)
		else
			render 'new'
		end
	end

	def destroy
			@origin.destroy
			flash[:success] = 'タグを削除しました'
			redirect_to origin_path
	end


	private

	def origin_params
		params.require(:origin).permit(:content)
	end

	def set_origin
		@origin = Origin.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.find_by(email: params[:session][:email].downcase)
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			flash[:info] = "#{@user.name}様がログインしました"
			redirect_to root_path
		else
			flash[:danger] = 'invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @links = []
    bunruis = Origin.all.pluck(:id)
    bunruis.each do |bunrui|
      link_temp = current_user.links.where(bunrui: bunrui).flatten if logged_in?
      @links << link_temp.reverse if link_temp
    end


		@link_box= []
		@links.each do |link|
			link.each do |k|
			@link_box << k
		end
		end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :show]
	before_action :correct_user, only: [:edit, :update]


	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "さぁ、始めましょう!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "変更内容を更新しました"
			redirect_to @user
		else
			render 'edit'
		end
	end


	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
																 :password_confirmation)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def correct_user
		redirect_to root_path if @user != current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  def img_gen
    	 @img_gen = "http://capture.heartrails.com/200x200/border?"
  end

  def init_tag
     @init_tag = Origin.where(user_id: nil)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="copyright">© <%= Date.today.year %> ONELINK.</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<div class="row">
			<%= link_to image_tag("logo.png"), root_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% unless logged_in? %>
					<li><%= link_to "新規登録" , signup_path %></li>
					<li><%= link_to "ログイン", login_path %></li>
				<% else %>
					<li>
						<%= link_to root_path(current_user), class: "link-add" do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true">Home</span>
					</li>
					<% end %>
					<li>
						<%= link_to new_link_path(current_user), class: "link-add" do %>
						<span class="glyphicon glyphicon-plus" aria-hidden="true">
							リンクを追加</span>
						<% end %>
					</li>
					<li>
						<%= link_to origin_path(current_user) do %>
						<span class="glyphicon glyphicon-tags" aria-hidden="true">タグ管理</span>
					</li>
					<% end %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-user" aria-hidden="true">
								<%= current_user.name %></span>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "プロフィール", current_user %></li>
							<li><%= link_to "設定", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "ログアウト", logout_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Onelink</title>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= javascript_include_tag 'assets/flash' %>
		<%= javascript_include_tag 'assets/jquery.fademover' %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag %>
		<script>
			$(document).ready(function () {
				$("#fade").fadeMover({'effectType': 1, 'inSpeed': 600, 'outSpeed': 600, 'nofadeOut': 'nonmover'});
			});
		</script>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div id="fade">
			<div class="container waku">
				<% flash.each do |message_type, message| %>
				<div id="flash_msg" class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
				<%= yield %>
			</div>
		</div>
		<%= render "layouts/footer" %>
	</body>
</html>

app/views/links/edit.html.erb
<h1>編集</h1>

<div class="editpic">
	<%= image_tag( img_gen + @link.url ) %>
</div>

<%= form_for(@link) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">URL</h3>
		</div>
		<div class="panel-body">
			<%= @link.url %>
		</div>

	</div>
	<%= f.label :タイトル %>
	<%= f.text_field :title %>
	<%= f.label :分類 %>
	<%= f.collection_select :bunrui, @current_tag, :id, :content %>
</div>

<%= f.submit "更新", class: "btn btn-primary" %>
<% end %>

app/views/links/new.html.erb
<h1>リンク登録</h1>

<%= form_for(@link) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="field">
	<%= f.label :URL %>
	<%= f.text_field :url, placeholder: "http or https..." %>
	<%= f.label :タグ %>
	<%= f.collection_select :bunrui, @tags, :id, :content %>
</div>

<%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/origins/edit.html.erb
<h1>タグ編集</h1>

<div class="tag_link_num">
	<h4>
		<span>Total:
			<%= pluralize(@links.count, "links") %></span>
	</h4>
</div>

<% if @links.empty? %>
	<%= link_to "", origin_path(@origin.id), :method => "delete", class: "glyphicon glyphicon-remove-circle", data: { confirm: '削除してもよろしいですか？' } %>
<% else %>
	<%= link_to "", origin_path(@origin.id), class: "glyphicon glyphicon-question-sign", data: { confirm: 'このタグで設定されているリンクが存在します、削除するには該当リンクのタグを変更してください。' } %>
<% end %>

<%= form_for(@origin) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">旧タグ名</h3>
			</div>
			<div class="panel-body">
				<%= @origin.content %>
			</div>
		</div>

		<%= f.label :新タグ名 %>
		<%= f.text_field :content, placeholder: "お気に入り" %>
	</div>
	<%= f.submit "更新", class: "btn btn-primary" %>

	<% @links.each do |k| %>
		<div class="tag_waku">
			<div class="item-box">
				<div class="image">
					<div class="img-wrap">
						<%= link_to image_tag( img_gen + k.url ), k.url, :target => "_blank", class: "nonmover" %>
						<%= link_to k.title, k.url, :target => "_blank", class: "nonmover" %>
						<div class="aicon">
							<%= link_to "", link_path(k.id), :method => "delete",
								class: "glyphicon glyphicon-trash", data: { confirm: '削除してもよろしいですか？'} %>
							<%= link_to "" , edit_link_path(k.id) , class: "glyphicon glyphicon-pencil" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% end %>

app/views/origins/new.html.erb
<h1>タグ追加</h1>

<%= form_for(@origin) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="field">
	<%= f.label :タグ名 %>
	<%= f.text_field :content, placeholder: "お気に入り" %>
</div>
<%= f.submit "追加", class: "btn btn-primary" %>
<% end %>

app/views/origins/show.html.erb
<h1>タグ一覧</h1>

<h4>
	<span>Total:
		<%= pluralize(current_user.origins.count, "tags") %></span>
</h4>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Myタグ</h3>
	</div>
	<div class="panel-body">

		<% @tags.each do |f| %>
		<ul>
			<%= f.content %>
			<%= link_to "", edit_origin_path(f.id), class:"glyphicon glyphicon-wrench" %>
		</ul>
		<hr>
		<% end %>

		<% if @tags.empty? %>
		*タグが設定されていません*
		<% end %>

	</div>
</div>

<%= link_to "タグ追加", new_origin_path(current_user), class: "btn btn-primary" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains
			<%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_num.html.erb
<span>Total：<%= pluralize(current_user.links.count, "link") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="container-fluid">
	<%= render 'shared/num' %>

	<% @links.each do |link| %>
	<div class="row">
		<% if link.first.present? %>
		<% tag = link.first.bunrui %>
		<div class="daimei">
			<% @tag = Origin.find(tag).content %>
			<h3>
				<div class="glyphicon glyphicon-tags">
					<%= @tag %>
				</div>
			</h3>
		</div>
		<% end %>

		<% link.each do |k| %>
		<div class="item-box">
			<div class="image">
				<div class="img-wrap">
					<%= link_to image_tag( img_gen + k.url ), k.url, :target => "_blank", class: "nonmover" %>
					<%= link_to k.title, k.url, :target => "_blank", class: "nonmover" %>
					<div class="aicon">
						<%= link_to "", link_path(k.id), :method => "delete",
												class: "glyphicon glyphicon-trash", data: { confirm: '削除してもよろしいですか？'} %>
						<%= link_to "" , edit_link_path(k.id) , class: "glyphicon glyphicon-pencil" %>
					</div>
				</div>
			</div>
		</div>
		<% end %>
	</div>
	<% end %>
</div>

<div class="announce">
	<% if @link_box.empty? %>
	<h1 class="up">↑</h1>
	<h1>リンクを追加しましょう</h1>
	<% end %>
</div>

<% else %>
<div class="center jumbotron">
	<h1>ようこそOneLinkへ</h1>
	<%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/users/_user_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :名前 %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :メールアドレス %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :パスワード %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード再確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "決定", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1>設定</h1>

<%= render 'user_form' %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1>
	プロフィール
</h1>
<h4>
	<%= render 'shared/num' %>
</h4>
<h4 class="prof_tag_num">
	Total:
	<%= pluralize(current_user.origins.count, "tags") %>
</h4>

<h3>
	<div class="name">
		<span class="glyphicon glyphicon-user edit-icon" aria-hidden="true"></span>
		<%= @user.name %>
	</div>
</h3>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">メールアドレス</h3>
	</div>
	<div class="panel-body">
		<%= @user.email %>
	</div>
	<div class="panel-heading">
		<h3 class="panel-title">アカウント作成日</h3>
	</div>
	<div class="panel-body">
		<%= @user.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
	</div>
</div>